version: '3.7'
services:
  server:
    build: ./
    command: >
      bash -c "
      cd /app
      && npm install --only=production
      && npm run db:migrate:production
      && NODE_ENV=production node index.js"
    ports:
      - $SERVER_PORT_IN:$SERVER_PORT_IN
    volumes:
       - ./:/app
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:12.3-alpine
    ports:
      - $POSTGRES_PORT:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB

  nginx:
    image: nginx:1.19.1-alpine
    depends_on:
      - server
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - $SERVER_PORT_OUT:$SERVER_PORT_OUT

volumes:
  db:

